spring:
  application:
    name: user-svc
  datasource:
    url: <DB URL>
    username: <DB USERNAME>
    password: <DB PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate_ddl: true
  properties:
    hibernate:
      format_sql: true

services:
  shopping-cart:
    base-url: <BASE URL>
  notification:
    base-url: <BASE URL>

server:
  port: 0