spring:
  application:
    name: user-svc
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/ecom_platform
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate_ddl: true
  properties:
    hibernate:
      format_sql: true

services:
  shopping-cart:
    base-url: ${SHOPPING_CART_URL:http://localhost:8003/api/}
  notification:
    base-url: ${NOTIFICATION_URL:http://localhost:8005/api/}

server:
  port: 8001