services:
  psql:
    image: postgres:14-alpine
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecom-platform
    volumes:
      - psql-ecom-pltfrm:/var/lib/postgresql/
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    mem_limit: 300m
    restart: always
  # user_svc:
  #   image:

volumes:
  psql-ecom-pltfrm:
    
