spring:
  application:
    name: shopping-cart-svc
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/ecom_platform
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate_ddl: true
  properties:
    hibernate:
      format_sql: true

services:
  user:
    base-url: ${USER_URL:http://localhost:8001/api/}
  product:
    base-url: ${PRODUCT_URL:http://localhost:8002/api/}

server:
  port: 8003