spring:
  application:
    name: notification-svc
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/ecom_platform
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate_ddl: true
  properties:
    hibernate:
      format_sql: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    from: ${MAIL_FROM}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8005